# Generated by Django 3.0.7 on 2020-06-15 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 18, 24, 28, 365013, tzinfo=utc), verbose_name='ads created date'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='centent',
            field=models.CharField(max_length=200),
        ),
    ]
